// Code generated by devtool; DO NOT EDIT.
package notion

import "github.com/Masterminds/semver/v3"

var (
	// Version is the version of go-notion.
	Version = semver.MustParse("0.1.12")

	// GoVersion declares what version of Go should be used.
	GoVersion = semver.MustParse("1.20.2")
)
